name: C++ Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile project
      run: g++ main.cpp student.cpp course.cpp -o app

    - name: Run program (basic test)
      run: echo -e "3" | ./app
